# Site settings
title: Leo G Dion
email: me@leogdion.name
description: |
  Entrepreneur, small business, father and husband. Interests include technology, movies, games, history and faith.

baseurl: ""
url: "http://leogdion.com"
twitter_username: leogdion
github_username:  leogdion

# Build settings
markdown: kramdown
permalink: pretty
